/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.ThuongHieu;
import Service.ThuongHieuService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class panelThuongHieu extends javax.swing.JDialog {
private ThuongHieuService serviceth = new ThuongHieuService();
private DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form panelThuongHieu
     */
    public panelThuongHieu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        FillTH();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthemthuonghieu = new javax.swing.JButton();
        btnxoathuonghieu = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        tbldsthuonghieu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txttenthuonghieu = new javax.swing.JTextField();
        btnsuathuonghieu = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnthemthuonghieu.setText("Thêm");
        btnthemthuonghieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemthuonghieuActionPerformed(evt);
            }
        });

        btnxoathuonghieu.setText("Xóa");
        btnxoathuonghieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoathuonghieuActionPerformed(evt);
            }
        });

        tbldsthuonghieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Tên thương hiệu"
            }
        ));
        tbldsthuonghieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldsthuonghieuMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(tbldsthuonghieu);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thương hiệu");

        txttenthuonghieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenthuonghieuActionPerformed(evt);
            }
        });

        btnsuathuonghieu.setText("Sửa");
        btnsuathuonghieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuathuonghieuActionPerformed(evt);
            }
        });

        jLabel27.setText("Tên thuộc tính");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(btnthemthuonghieu))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttenthuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnsuathuonghieu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnxoathuonghieu)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttenthuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsuathuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthemthuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoathuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemthuonghieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemthuonghieuActionPerformed
        if (checkthuonghieu()) {
            ThuongHieu cl = new ThuongHieu();
            cl.setTen(txttenthuonghieu.getText());
            boolean clResult = serviceth.them(cl);
            if (clResult) {
                FillTH();
            }
        }
    }//GEN-LAST:event_btnthemthuonghieuActionPerformed

    private void btnxoathuonghieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoathuonghieuActionPerformed
        int i = tbldsthuonghieu.getSelectedRow();
        ThuongHieu th1 = new ThuongHieu();
        th1.setTen(txttenthuonghieu.getText());
        th1.setId(tbldsthuonghieu.getValueAt(i, 0).toString());
        boolean thResult = serviceth.an(th1);
        if (thResult) {
            FillTH();
        }
    }//GEN-LAST:event_btnxoathuonghieuActionPerformed

    private void tbldsthuonghieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldsthuonghieuMouseClicked
        int i = tbldsthuonghieu.getSelectedRow();
        Show(i);
    }//GEN-LAST:event_tbldsthuonghieuMouseClicked

    private void txttenthuonghieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenthuonghieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenthuonghieuActionPerformed

    private void btnsuathuonghieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuathuonghieuActionPerformed
        int i = tbldsthuonghieu.getSelectedRow();
        if (checkthuonghieu()) {
            ThuongHieu th1 = new ThuongHieu();
            th1.setTen(txttenthuonghieu.getText());
            th1.setId(tbldsthuonghieu.getValueAt(i, 0).toString());
            boolean thResult = serviceth.sua(th1);
            if (thResult) {
                FillTH();
            }
        }
    }//GEN-LAST:event_btnsuathuonghieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                panelThuongHieu dialog = new panelThuongHieu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void FillTH() {
        

        dtm = (DefaultTableModel) tbldsthuonghieu.getModel();
        dtm.setRowCount(0);
        for (ThuongHieu x : serviceth.gettAll()) {
            dtm.addRow(new Object[]{
                x.getId(), x.getTen()
            });
        }
    }
    public void Show(int i){
        txttenthuonghieu.setText(tbldsthuonghieu.getValueAt(i, 1).toString());
    }
    public boolean checkthuonghieu() {
        boolean check = true;
        if (txttenthuonghieu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập giá trị");
            check = false;
        } else {
            for (ThuongHieu x : serviceth.gettAll()) {
                if (x.getTen().contains(txttenthuonghieu.getText())) {
                    JOptionPane.showMessageDialog(this, "Đã tồn tại");
                    check = false;
                    break;
                }
            }
        }

        return check;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsuathuonghieu;
    private javax.swing.JButton btnthemthuonghieu;
    private javax.swing.JButton btnxoathuonghieu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JTable tbldsthuonghieu;
    private javax.swing.JTextField txttenthuonghieu;
    // End of variables declaration//GEN-END:variables
}
