/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ChatLieu;
import Model.MauSac;
import Model.PhanLoai;
import Model.SanPham;
import Model.SanPhamChiTiet;
import Model.ThuongHieu;
import Model.XuatXu;
import Service.ChatLieuService;
import Service.MauSacService;
import Service.PhanLoaiService;
import Service.SPCTService;
import Service.SanPhamService;
import Service.ThuongHieuService;
import Service.XuatXuService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class viewSPCT extends javax.swing.JFrame {
private DefaultTableModel dtm = new DefaultTableModel();
private SanPhamService spservice = new SanPhamService();
private SPCTService service = new SPCTService();
private ChatLieuService cls = new ChatLieuService();
private PhanLoaiService pls = new PhanLoaiService();
private MauSacService mss = new MauSacService();
private ThuongHieuService ths = new ThuongHieuService();
private XuatXuService xxs = new XuatXuService();
private static SanPham sp;
    /**
     * Creates new form viewSPCT
     * @param id
     */
    public viewSPCT(SanPham sp) {
        initComponents();
        LoadCBO();
        setLocationRelativeTo(null);
        lblmasp.setText(sp.getMaSP());
        lbltensp.setText(sp.getTenSP());
        fillTable(service.findSPCTByIDSP(sp.getId()));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthemth = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbltensp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblmasp = new javax.swing.JLabel();
        txtgia = new javax.swing.JTextField();
        cboxuatxu = new javax.swing.JComboBox<>();
        cbothuonghieu = new javax.swing.JComboBox<>();
        btnthemxx = new javax.swing.JButton();
        cbomausac = new javax.swing.JComboBox<>();
        tbmthemms = new javax.swing.JButton();
        cbophanloai = new javax.swing.JComboBox<>();
        btnthemcl = new javax.swing.JButton();
        btnthemphanloai = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btndaxoa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnmoi = new javax.swing.JButton();
        cbochatlieu = new javax.swing.JComboBox<>();
        btnxoa = new javax.swing.JButton();
        txtsoluong = new javax.swing.JTextField();
        btnsua = new javax.swing.JButton();
        lblspanh = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblspct = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtamota = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkhoiluong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtkichthuoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnthemth.setText("+");
        btnthemth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemthActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID:");

        lbltensp.setText("MaSP");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Sản phẩm chi tiết");

        lblmasp.setText("MaSP");

        txtgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cboxuatxu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxuatxu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbothuonghieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbothuonghieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnthemxx.setText("+");
        btnthemxx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemxxActionPerformed(evt);
            }
        });

        cbomausac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbomausac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbmthemms.setText("+");
        tbmthemms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbmthemmsActionPerformed(evt);
            }
        });

        cbophanloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbophanloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnthemcl.setText("+");
        btnthemcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemclActionPerformed(evt);
            }
        });

        btnthemphanloai.setText("+");
        btnthemphanloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemphanloaiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Xuất xứ:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Thương hiệu:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Chất liệu:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Phân loại:");

        btndaxoa.setText("Đã xóa");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Màu sắc:");

        btnmoi.setText("Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        cbochatlieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbochatlieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnxoa.setText("Xóa");

        txtsoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        lblspanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mô tả:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Giá:");

        tblspct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Phân loại", "Chất liệu", "Thương hiệu", "Màu sắc", "Xuất xứ", "Kích thước", "Khối lượng", "Số lượng", "Giá", "Mô tả", "Ảnh"
            }
        ));
        tblspct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblspctMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblspct);

        txtamota.setColumns(20);
        txtamota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtamota.setRows(5);
        jScrollPane1.setViewportView(txtamota);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số lượng:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Khối lượng:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Kích thước:");

        txtkhoiluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã sản phẩm:");

        txtkichthuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(665, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblspanh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblmasp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbltensp, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtkhoiluong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtkichthuoc))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbochatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbophanloai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbomausac, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbothuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnthemth)
                                            .addComponent(btnthemphanloai)
                                            .addComponent(btnthemcl)
                                            .addComponent(tbmthemms)
                                            .addComponent(btnthemxx))
                                        .addGap(21, 21, 21))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnxoa)
                                    .addComponent(btnmoi))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnthem)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btndaxoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnsua, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(cbophanloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnthemphanloai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cbomausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbmthemms, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(cbochatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnthemcl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cbothuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnthemth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cboxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnthemxx, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmoi)
                            .addComponent(btnthem))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnxoa)
                            .addComponent(btnsua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndaxoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(lblmasp)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(lbltensp))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtkichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtkhoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblspanh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemthActionPerformed
        panelThuongHieu dialog = new panelThuongHieu(this, true);
        dialog.setVisible(true);
        dialog.setSize(780, 437);
        dialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnthemthActionPerformed

    private void btnthemxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemxxActionPerformed
        
    }//GEN-LAST:event_btnthemxxActionPerformed

    private void tbmthemmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbmthemmsActionPerformed
        
    }//GEN-LAST:event_tbmthemmsActionPerformed

    private void btnthemclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemclActionPerformed
        
    }//GEN-LAST:event_btnthemclActionPerformed

    private void btnthemphanloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemphanloaiActionPerformed
        
    }//GEN-LAST:event_btnthemphanloaiActionPerformed

    private void tblspctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblspctMouseClicked
        // TODO add your handling code here:
        int i= tblspct.getSelectedRow();
        Show(i);
    }//GEN-LAST:event_tblspctMouseClicked

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if(service.ThemSPCT(readFormSPCT())>0){
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            fillTable(service.findSPCTByIDSP(spservice.findSPByMa(lblmasp.getText()).getId()));
        }else{
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if(service.SuaSPCT(readFormSPCT())>0){
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            fillTable(service.findSPCTByIDSP(spservice.findSPByMa(lblmasp.getText()).getId()));
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SanPham sp1 = new SanPham(sp.getId(), sp.getMaSP(), sp.getTenSP(), sp.getTrangThai());
                new viewSPCT(sp1).setVisible(true);
            }
        });
    }
    private void fillTable(List<SanPhamChiTiet> l){
        dtm = (DefaultTableModel) tblspct.getModel();
        dtm.setRowCount(0);
        for(SanPhamChiTiet x:l){
            dtm.addRow(new Object[]{
                x.getId(),pls.findPL(x.getIdpl()).getTen(),cls.findCL(x.getIdcl()).getTen(),ths.findTH(x.getIdth()).getTen(),mss.findMS(x.getIdms()).getTen(),
                xxs.findXX(x.getIdxx()).getTen(),x.getKichThuoc(),x.getKhoiLuong(),x.getSoLuong(),x.getGia(),x.getMoTa(),x.getAnh()
            });
        }
    }
    private void LoadCBO(){
        cbochatlieu.removeAllItems();
        cbomausac.removeAllItems();
        cbophanloai.removeAllItems();
        cbothuonghieu.removeAllItems();
        cboxuatxu.removeAllItems();
        for(ChatLieu x:cls.gettAll()){
            cbochatlieu.addItem(x.getTen());
        }
        for(PhanLoai x:pls.gettAll()){
            cbophanloai.addItem(x.getTen());
        }
        for(MauSac x:mss.gettAll()){
            cbomausac.addItem(x.getTen());
        }
        for(ThuongHieu x:ths.gettAll()){
            cbothuonghieu.addItem(x.getTen());
        }
        for(XuatXu x:xxs.gettAll()){
            cboxuatxu.addItem(x.getTen());
        }
    }
    private void Show(int i){
        txtid.setText(tblspct.getValueAt(i, 0).toString());
        cbophanloai.setSelectedItem(tblspct.getValueAt(i, 1).toString());
        cbochatlieu.setSelectedItem(tblspct.getValueAt(i, 2).toString());
        cbothuonghieu.setSelectedItem(tblspct.getValueAt(i, 3).toString());
        cbomausac.setSelectedItem(tblspct.getValueAt(i, 4).toString());
        cboxuatxu.setSelectedItem(tblspct.getValueAt(i, 5).toString());
        txtkichthuoc.setText(tblspct.getValueAt(i, 6).toString());
        txtkhoiluong.setText(tblspct.getValueAt(i, 7).toString());
        txtsoluong.setText(tblspct.getValueAt(i, 8).toString());
        txtgia.setText(tblspct.getValueAt(i, 9).toString());
        txtamota.setText(tblspct.getValueAt(i, 10).toString());
    }
    public SanPhamChiTiet readFormSPCT(){
        SanPhamChiTiet spct = new SanPhamChiTiet();
        spct.setIdsp(spservice.findSPByMa(lblmasp.getText()).getId());
        spct.setIdpl(pls.findidPL(cbophanloai.getSelectedItem().toString()).getId());
        spct.setIdms(mss.findidMS(cbomausac.getSelectedItem().toString()).getId());
        spct.setIdcl(cls.findidCL(cbochatlieu.getSelectedItem().toString()).getId());
        spct.setIdth(ths.findidTH(cbothuonghieu.getSelectedItem().toString()).getId());
        spct.setIdxx(xxs.findidXX(cboxuatxu.getSelectedItem().toString()).getId());
        spct.setKichThuoc(txtkichthuoc.getText());
        spct.setKhoiLuong(Float.parseFloat(txtkhoiluong.getText()));
        spct.setSoLuong(Integer.parseInt(txtsoluong.getText()));
        spct.setGia(Float.parseFloat(txtgia.getText()));
        spct.setMoTa(txtamota.getText());
        return spct;
    }
    public void Clear(){
        txtamota.setText("");
        txtgia.setText("");
        txtsoluong.setText("");
        txtkhoiluong.setText("");
        txtkichthuoc.setText("");
        cbochatlieu.setSelectedIndex(0);
        cbomausac.setSelectedIndex(0);
        cbophanloai.setSelectedIndex(0);
        cbothuonghieu.setSelectedIndex(0);
        cboxuatxu.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndaxoa;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemcl;
    private javax.swing.JButton btnthemphanloai;
    private javax.swing.JButton btnthemth;
    private javax.swing.JButton btnthemxx;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbochatlieu;
    private javax.swing.JComboBox<String> cbomausac;
    private javax.swing.JComboBox<String> cbophanloai;
    private javax.swing.JComboBox<String> cbothuonghieu;
    private javax.swing.JComboBox<String> cboxuatxu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblmasp;
    private javax.swing.JLabel lblspanh;
    private javax.swing.JLabel lbltensp;
    private javax.swing.JTable tblspct;
    private javax.swing.JButton tbmthemms;
    private javax.swing.JTextArea txtamota;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkhoiluong;
    private javax.swing.JTextField txtkichthuoc;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
}
